// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClnSbThjzllVq_a11Eekm096m0wb70B8Y',
    appId: '1:528746242925:web:bfb935ca22270337eef064',
    messagingSenderId: '528746242925',
    projectId: 'mexpertztest',
    authDomain: 'mexpertztest.firebaseapp.com',
    storageBucket: 'mexpertztest.firebasestorage.app',
    measurementId: 'G-8CBXNK5K23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA-7-NgzXntzjAYc1OtdZm0bqW8nRr9p1U',
    appId: '1:528746242925:android:edc8f18962dd18deeef064',
    messagingSenderId: '528746242925',
    projectId: 'mexpertztest',
    storageBucket: 'mexpertztest.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJ04KSppa1i69qDrAXqyzNrDIktqxPhMM',
    appId: '1:528746242925:ios:5ee861442615419feef064',
    messagingSenderId: '528746242925',
    projectId: 'mexpertztest',
    storageBucket: 'mexpertztest.firebasestorage.app',
    iosBundleId: 'com.example.mexpertztest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJ04KSppa1i69qDrAXqyzNrDIktqxPhMM',
    appId: '1:528746242925:ios:5ee861442615419feef064',
    messagingSenderId: '528746242925',
    projectId: 'mexpertztest',
    storageBucket: 'mexpertztest.firebasestorage.app',
    iosBundleId: 'com.example.mexpertztest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClnSbThjzllVq_a11Eekm096m0wb70B8Y',
    appId: '1:528746242925:web:e2f8923c4da05e9aeef064',
    messagingSenderId: '528746242925',
    projectId: 'mexpertztest',
    authDomain: 'mexpertztest.firebaseapp.com',
    storageBucket: 'mexpertztest.firebasestorage.app',
    measurementId: 'G-Y376JMRECF',
  );
}
